/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'joao' at '5/12/17 11:47 AM' with Gradle 3.1
 *
 * @author joao, @date 5/12/17 11:47 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
