/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'joao' at '5/12/17 11:47 AM' with Gradle 3.1
 *
 * @author joao, @date 5/12/17 11:47 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
